# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ibettenc <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/04/09 13:43:25 by ibettenc          #+#    #+#              #
#    Updated: 2025/04/28 14:24:03 by ibettenc         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #
###################################################
## ARGUMENTS

NAME = libft.a

CFLAGS = -Wall -Werror -Wextra

CC = gcc

###################################################
## SOURCES

SRC = ft_isalpha.c ft_isdigit.c ft_isalnum.c ft_isascii.c \
      ft_isprint.c ft_strlen.c ft_memset.c ft_bzero.c \
       ft_memcpy.c ft_memmove.c ft_strlcpy.c ft_strlcat.c \
       ft_calloc.c ft_strdup.c ft_toupper.c ft_tolower.c \
       ft_strchr.c ft_strncmp.c ft_memchr.c ft_memcmp.c \
       ft_strnstr.c ft_atoi.c ft_strrchr.c ft_substr.c \
       ft_strjoin.c ft_strtrim.c ft_split.c ft_itoa.c \
       ft_strmapi.c ft_striteri.c ft_putchar_fd.c \
       ft_putstr_fd.c ft_putendl_fd.c ft_putnbr_fd.c

SRCB = ft_lstadd_back_bonus.c ft_lstadd_front_bonus.c ft_lstclear_bonus.c \
	ft_lstdelone_bonus.c ft_lstiter_bonus.c ft_lstlast_bonus.c \
	ft_lstmap_bonus.c ft_lstnew_bonus.c ft_lstsize_bonus.c

OBJ = $(SRC:.c=.o)
OBJB = $(SRCB:.c=.o)

###################################################
## RULES

all: $(NAME)

$(NAME): $(OBJ)
	ar rcs $(NAME) $(OBJ)

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@
##################################################
## POUR TESTER
#
#so:
#	$(CC) -fPIC $(CFLAGS) $(SRC) $(SRCB)
#	gcc -shared -o libft.so $(OBJ) $(OBJB)
#so:
#	$(CC) -nostartfiles -fPIC $(CFLAGS) $(SRC) $(SRCB)
#	gcc -nostartfiles -shared -o libft.so $(OBJ) $(OBJB)
##################################################
## BONUS

bonus: $(OBJ) $(OBJB)
	ar rcs $(NAME) $(OBJ) $(OBJB)

##################################################
## CLEAN

clean:
	rm -f $(OBJ) $(OBJB)

fclean: clean
	rm -f $(NAME)

re: fclean all

.PHONY: all bonus clean fclean re
